---
title: "Add permit lat/longs"
author: "Alan Jackson"
date: "April 23, 2019"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(skimr)
library(sf)
library(nngeo)
library(units)


knitr::opts_chunk$set(echo = TRUE)
```

##  do a join between permit geocoding and my geocoding

```{r join databases}
st_drop_geometry <- function(x) {
  if(inherits(x,"sf")) {
      x <- st_set_geometry(x, NULL)
      class(x) <- 'data.frame'
  }
  return(x)
}

Geotable <- readRDS("~/Dropbox/CrimeStats/CensusGeoTable_progress.rds")
Permits <- readRDS("~/Dropbox/CrimeStats/PermitDB_Geocode.rds")

Geotable <- Geotable %>% 
  select(Address, match_address, Beat, n, lat, long, geocode_status, status) %>% 
  mutate(Address=toupper(Address)) %>% 
  mutate(Address=str_remove(Address," , .*")) %>% 
  filter(!is.na(lat))

Permits <- Permits %>% 
  select(Address, Lat, Lon) %>% 
  mutate(Address=str_replace(Address, "000-099", "0-99")) %>% 
  group_by(Address) %>% 
  summarise(NewLat=mean(Lat), NewLon=mean(Lon)) %>% 
  mutate(oldAddress=Address) %>% 
  mutate(Address=toupper(Address)) %>% 
  mutate(Address=str_remove(Address," , .*")) 

# Add Beat to Permits

Beats <- read_sf('/home/ajackson/Dropbox/CrimeStats/BeatPolys/Houston_Police_Beats.shp')

#   find points in polygons
#   since beats don't overlap (I hope), let's just grab the array index
#   instead of creating a huge matrix

# first make Permits an sf object

googlecrs <- 4326
Permits <- st_as_sf(Permits, coords=c("NewLon", "NewLat"),
                    crs=googlecrs, agr = "identity")
Geotable <- st_as_sf(Geotable, coords=c("long", "lat"),
                    crs=googlecrs, agr = "identity")

keep <- Permits
# intersect

Geotable <- st_join(Geotable, Beats, join=st_nn, maxdist=500) 

#   Which records have conflicting beat information?

Geotable_conflicts <- Geotable %>% 
  filter(Beats!=Beat) %>% 
  select(Address, match_address, Beat, n, geocode_status, status, Beats)

#   What is distance between point and presumed beat?

tempGeo <- Geotable %>% 
  st_drop_geometry() %>% 
  select(Address, Beat)

tempBeats <- Beats %>% 
  rename(Beat=Beats)   

tempBeats <- 
  left_join(tempGeo %>% as.data.frame(), tempBeats %>% as.data.frame(), by = "Beat") 

tempBeats <-  st_sf(tempBeats, sf_column_name = 'geometry')

Geotable_beatdistance <- 
  st_distance(Geotable, tempBeats, by_element = TRUE)

Geotable$distance <-  Geotable_beatdistance  

Geotable <- Geotable %>% 
  select(Address, match_address, Beat, n, geocode_status, status, distance) %>% 
  filter(distance>set_units(250,"meters")) %>% 
  filter(n>2)

Permits <- st_join(Permits, Beats, join=st_nn, maxdist=500) 

Permits <- Permits %>% 
  select(Address, oldAddress, Beats)
                      
#   Final join of permit data to crime data

Final <- full_join(Geotable, Permits, by="Address")

```


##    Test output in various ways

- Look at distance distribution between nominally similar points
- Count unique addresses for both input datasets
- compare distances census vs google against permits

```{r test data}

Final <- Final %>% 
  mutate(dist=sqrt((((lat-NewLat)*364191)**2) +
                   ((long-NewLon)*311695)**2)) 
  skim()
  ggplot(aes(x=dist)) +
    geom_histogram(binwidth=10)

```


