---
title: "MakeGeocodingFile"
author: "Alan Jackson"
date: "8/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stringr)
library(dplyr)

options(stringsAsFactors = FALSE)

geotable <- readRDS("~/Dropbox/CrimeStats/GeoTable_19Aug2019.rds")

generated <- readRDS("~/Dropbox/CrimeStats/Generated_Coordinates.rds")

```

## Make geocoding file

  * blank out generated locations and then add back
   
  * intersect geotable with:
      + zipcode
      + census tract
      + neighborhood
  * end up with Address, Beat, Match_address, Lat, Long, Tract. Block, Zip, Neighborhood
     Source (census, google, manual, generated), Status (success, failed, impossible)
     
  * Make neural net training set (similar but also include raw address)


```{r add generated locations}

#####   check_match
check_match <- function(test_Address, testdata){
    # Did I already succeed at this match somewhere?
    a <- testdata %>% filter(test_Address == Address,
                              status=="success" )
    if (nrow(a)>0){
      return(a)
    } else {return(FALSE)}
}

#   usage:
#   a <- check_match(geotable[i,], previous_match)
#   if (is_tibble(a)) {geotable[i,4:10] <- a[1,4:10]
#      print("found previous match")}

#   fix double blank in generated filend missing blank in geotable

generated$Address <- str_replace(generated$Address, "  ", " ")
geotable$Address <- str_replace(geotable$Address, "n,", "n ,")
geotable$Address <- str_replace(geotable$Address, "9\\([A-Z]\\)", "9 \\1")

# change manual redo to manual (what did I do that for anyway?)

geotable$geocode_status <- str_replace(geotable$geocode_status, "manual redo", "manual")

####   Spin through file and match generated
for (i in begin:nrow(geotable)) {
  
  # first blank out generated data, in case it is bogus
  
  if(geotable[i,]$geocode_status == "generated") {
    geotable[i,]$lat <- NA
    geotable[i,]$long <- NA
    geotable[i,]$geocode_status <- "redo"
    geotable[i,]$status <- "redo"
    print(paste("-- clear -->",geotable[i,]$Address))
    
  }

  if(geotable[i,]$geocode_status!="manual"){ 
    a <- check_match(geotable[i,]$Address, generated)
    if (is_tibble(a)) {
      geotable[i,6:7] <- a[1,2:3]
      geotable[i,]$geocode_status <- "generated"
      geotable[i,]$status <- "success"
      print(paste("-- update -->",geotable[i,]$Address))
      next
    }
  }
}

####   Spin through file and match against self
for (i in begin:nrow(geotable)) {
  
  if(grepl("redo", geotable[i,]$geocode_status)){ 
    a <- check_match(geotable[i,]$Address, geotable)
    if (is_tibble(a)) {
      geotable[i,4:10] <- a[1,4:10]
      print(paste("-- update -->",geotable[i,]$Address))
      next
    }
  }
}


# summary of some fields

sort(unique(geotable$geocode_status))
sort(unique(geotable$status))

# Save file

saveRDS(geotable, "~/Dropbox/CrimeStats/GeoTable_22Aug2019_withgen.rds")

```

