---
title: "ReadHPDdata_2a"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")
library("stringr") # string tools
library("rvest")# web scraping
library("lettercase") # fiddle with letter case
library("lubridate")

PremiseTable = readRDS("/home/ajackson/mirrors/ajackson/crime/data/PremiseTable.rds")

knitr::opts_chunk$set(echo = TRUE)
```

```{r read premise code translation table in}
# read in table of premise code and make a dataset

url = "http://www.houstontx.gov/police/cs/beatpages/premise.htm"

premise <- url %>% 
  read_html() %>% 
  html_nodes(xpath='//table') %>% 
  html_table(header=TRUE)
premise <- premise[[1]]

# clean up descriptions to make more readable

premise$`Premise Description` <- str_title_case(str_lower_case(premise$`Premise Description`))
premise$`Premise Description` <- str_replace_all(premise$`Premise Description`," And ", " and ")
premise$`Premise Description` <- str_replace_all(premise$`Premise Description`," Of ", " of ")

# make compatible with monthly files

colnames(premise)[1] <- "Premise"

```


#   Set up to read in all the files for a district
#   http://www.houstontx.gov/police/cs/beatpages

```{r read district}
#   set year range, months, and district
year_range = str_pad(as.character(9:17),2,pad="0")
months = tolower(month.abb[1:12])
district <- "2a"
beats <- c("2a10","2a20","2a30","2a40","2a50","2a60")


# initialize empty data frame

df <- data.frame(Date=character(),
                 Hour=character(),
                 Offense_Type=character(),
                 Beat=character(),
                 Premise=character(),
                 Block_Range=character(),
                 Street=character(),
                 Type=character(),
                 Suffix=character(),
                 Num_Off=integer(),
                 stringsAsFactors=FALSE)

####################################
# now let's spin through the files
####################################
flag = FALSE
premiseflag = TRUE # months before June 2014 used premise codes - need to convert
for (yr in year_range)
{
  for (mon in months)
    {
    # Aug '17 at district is missing, so skip
    if ((yr == "17") && (mon == "aug")) {next}
    
    url = paste("http://www.houstontx.gov/police/cs/stats20",yr,"/",mon,yr,"/districts/",mon,yr,district,".htm", sep="")
    print(url)
    
# most of 2009 and January 2010 are different...
if ((yr=="09"&&mon %in% c("jan","feb","mar","apr","may","jun","jul","sep","nov")) || (yr=="10"&&mon=="jan")) {
  tempfile <- url %>% 
    read_html() %>% 
    html_nodes(xpath='/html/body/table') %>% 
    html_table(header=TRUE)
}
    else {
    # read in html table and parse into a data frame
    tempfile <- url %>% 
      read_html() %>% 
      html_nodes(xpath='/html/body/div/table') %>% 
      html_table(header=TRUE)
}
    tempfile <- tempfile[[1]]
    
    # June and July 2014 are missing the premise column
    if ((yr=="14")&&(mon=="jul" || mon=="jun")){
      tempfile <- tempfile %>% mutate(Premise=NA)
      tempfile <- tempfile[c(1,2,3,4,10,5,6,7,8,9)]
      premiseflag = FALSE
    }
    # Jan through May 2009 are missing the Num_Off column and have time instead of hour
    if ((yr=="09") && (mon %in% c("jan","feb","mar","apr","may"))){
      tempfile <- tempfile %>% mutate(Num_Off=NA)
      tempfile[,2] <- substr(tempfile[,2],1,nchar(tempfile[,2])-2)
      tempfile[,2] <- sub("^$", "00", tempfile[,2])
      tempfile$Block <- paste(as.character(tempfile$Block), as.character(tempfile$Block+99),sep="-")
    }
    # Remove nonsense columns
    tempfile <- select(tempfile,-starts_with("Field"))
    
    # Force consistent column names
    names(tempfile) <- c("Date","Hour","Offense_Type","Beat","Premise","Block_Range","Street","Type","Suffix","Num_Off")
    
    # some hour fields are borked with character data
    tempfile$Hour <- as.character(tempfile$Hour)
    
    # if an early file, replace premise codes with premise descriptions
    if (premiseflag){
      tempfile["Premise"] <- left_join(tempfile,premise, by="Premise")["Premise Description"]
    }
    # append to df
    df <- bind_rows(df, tempfile)
    
    # time to stop? 
    if ((yr == "17") && (mon == "nov")) {flag = TRUE; break}
  }
  if (flag) {break}
}

```

#     August 2017 district files missing, so read individual beat files instead

```{r read in August 2017 by beat}

beats <- c("2a10","2a20","2a30","2a40","2a50","2a60")

for (beat in beats)
    {
    
    url = paste("http://www.houstontx.gov/police/cs/stats2017/aug17/aug17",beat,".htm", sep="")
    print(url)
    

    # read in html table and parse into a data frame
    tempfile <- url %>% 
      read_html() %>% 
      html_nodes(xpath='/html/body/div/table') %>% 
      html_table(header=TRUE)
    tempfile <- tempfile[[1]]
    
    # Remove nonsense columns
    tempfile <- select(tempfile,-starts_with("Field"))
    
    # Force consistent column names
    names(tempfile) <- c("Date","Hour","Offense_Type","Beat","Premise","Block_Range","Street","Type","Suffix","Num_Off")
    
    # some hour fields are borked with character data
    tempfile$Hour <- as.character(tempfile$Hour)
    
    # append to df
    df <- bind_rows(df, tempfile)
  }
#################################
# Save the raw file
#################################

##---new---##
saveRDS(df, file="~/Dropbox/CrimeStats/District2aRawData.rds")

```


```{r generate some basic statics on data quality}

#################################
# How many nulls everywhere?
#################################
df %>%
    map_df(function(x) sum(is.na(x))) %>%
    gather(feature, num_nulls) %>%
    print(n = 100)
```


```{r Check Dates }
#################################
# Dates
#################################
#--- plot number of incident records by date
a <- table(df$Date)
barplot(a)
hist(a, breaks=20)
#--- print the top and bottom dates
b <- df %>%
  group_by(Date) %>%
  summarise(num=n()) 
arrange(b,num) %>% head(120)
arrange(b,num) %>% tail(5)
############
##  convert date string to actual date, and then trim bad dates out
############
df$Date <- mdy(df$Date)
df <- df %>%
  filter(between(Date,mdy("1/1/2009"),mdy("1/1/2018")))
Total_Incidents_per_day <- table(df$Date)
hist(Total_Incidents_per_day, breaks=20)
```


```{r Check Hour field}
#################################
# Hour
#################################

unique(df$Hour)
# remove non-numerics and change to integer
df$Hour <- str_replace_all(df$Hour,"\\D","")
df$Hour <- as.integer(df$Hour)

unique(df$Hour)
ggplot(data=df) +
  geom_bar(aes(x=Hour)) +
  labs(title=paste("Incidents per Hour, District",district))
```

```{r Check Offense_Type field}
#################################
# Offense_Type
#################################

unique(df$Offense_Type)

#   clean up Offense_Type and look again for issues

df$Offense_Type <-  str_replace(df$Offense_Type,"\n\\s+"," ") # get rid of extra spaces and \n
df$Offense_Type <-  str_replace(df$Offense_Type,"Forcible ","") # get rid of Forcible
df$Offense_Type <-  str_replace(df$Offense_Type,"AutoTheft","Auto Theft") # add space
df$Offense_Type <-  str_replace(df$Offense_Type," of a Motor Vehicle","") # just burglary
df$Offense_Type <-  str_replace(df$Offense_Type," & Nonnegligent Manslaughter","") # just murder
#   Bar chart of various incidents
ggplot(data=df) +
  geom_bar(aes(x=Offense_Type)) +
  labs(title=paste("Incidents per Offense Type, District",district)) +
  coord_flip()
# Plot of incidents per month vs date
per_month = df %>% 
  mutate(mon = as.numeric(format(Date, "%m")), yr = as.numeric(format(Date, "%Y"))) %>%
  mutate(YrMon=yr+mon/12) %>%
  group_by(YrMon, Offense_Type) %>%
  summarize(total=n())

ggplot(data=per_month, mapping=aes(x=YrMon, y=total, color=Offense_Type)) +
  geom_point() +
  geom_line() +
  labs(title="Total incidents in the Heights ", y="Total incidents per month", x="Averaged Monthly") 

#   filter out past 2010 to get a better view of what is going on
per_month = df %>% 
  mutate(mon = as.numeric(format(Date, "%m")), yr = as.numeric(format(Date, "%Y"))) %>%
  mutate(YrMon=yr+mon/12) %>%
  filter(YrMon<2011) %>%
  group_by(YrMon, Offense_Type) %>%
  summarize(total=n())
ggplot(data=per_month, mapping=aes(x=YrMon, y=total, color=Offense_Type)) +
  geom_point() +
  geom_line() +
  labs(title="Total incidents in the Heights expanded", y="Total incidents per month", x="Averaged Monthly") 

#     Get rid of all data prior to June 2009, since it cannot be compared with later data

df <- df %>%
  filter(between(Date,mdy("6/1/2009"),mdy("1/1/2018")))

```

```{r Check Beat data}
#################################
# Beat
#################################

unique(df$Beat)
# remove non-alphanumerics
df$Beat <- str_replace_all(df$Beat,"\\W","")

```

```{r Check Premise data}
#################################
# Premise
#################################
per_month = df %>% 
  mutate(mon = as.numeric(format(Date, "%m")), yr = as.numeric(format(Date, "%Y"))) %>%
  mutate(YrMon=yr+mon/12) %>%
  group_by(YrMon) %>%
  summarize(count=sum(is.na(Premise)))

ggplot(data=per_month, mapping=aes(x=YrMon, y=count)) +
  geom_point() +
  labs(title="Blank Premise fields per month", y="Total blanks per month", x="Averaged Monthly") 

#   make more manageable by changing NULL to UNK
df$Premise[is.na(df$Premise)] <- "Other or Unknown"

sort(table(df$Premise), decreasing=TRUE)

#   Clean up obvious issues

df$Premise <-  str_replace(df$Premise,"\n\\s+"," ") # get rid of extra spaces and \n
df$Premise <- sub("^$","Other or Unknown", df$Premise)
df$Premise <- str_replace_all(df$Premise, "  "," ") # 2 spaces to 1
df$Premise <- str_replace_all(df$Premise, " and "," & ") # and to &
df$Premise <- str_replace_all(df$Premise, " And "," & ")
df$Premise <- str_replace_all(df$Premise, "/"," or ") # / to or
df$Premise <- str_replace_all(df$Premise, ", ",",") # comma space to comma
df$Premise <- str_replace_all(df$Premise, "ment Rent","ment or Rent")
df$Premise <- str_replace_all(df$Premise, "Saving ","Savings ")
df$Premise <- str_replace_all(df$Premise, "rch,Syn","rch or Syn")
df$Premise <- str_replace_all(df$Premise, ",or "," or ")
df$Premise <- str_replace_all(df$Premise, "Sup\\.","Supplies")
df$Premise <- str_replace_all(df$Premise, "Field or Woods","Field,Woods,Forest,Park")
df$Premise <- str_replace_all(df$Premise, "Tv","TV Store")
df$Premise <- str_replace_all(df$Premise, "Grocery Store","Grocery")
df$Premise <- str_replace_all(df$Premise, "Pool$","Pool,Spa")
df$Premise <- str_replace_all(df$Premise, "Hse,Indr","House,Indoor")
df$Premise <- str_replace_all(df$Premise, "Hotel,Motel,Inn,Etc","Hotel or Motel or Etc")
df$Premise <- str_replace_all(df$Premise, "Laundry,Dry Cleaners,Washaterias","Laundry or Dry Cleaners or Washaterias")
df$Premise <- str_replace_all(df$Premise, "Misc\\.","Miscellaneous")
df$Premise <- str_replace_all(df$Premise, "Hme","Home ")
df$Premise <- str_replace_all(df$Premise, "Etc\\.","Etc")
df$Premise <- str_replace_all(df$Premise, "Other,Unknown or Not Listed","Other or Unknown")
df$Premise <- str_replace_all(df$Premise, "Not Listed","Other or Unknown")
df$Premise <- str_replace_all(df$Premise, "Swim ","Swimming ")
df$Premise <- str_replace_all(df$Premise, "n,R","n or R")
df$Premise <- str_replace_all(df$Premise, "d,S","d or S")
df$Premise <- str_replace_all(df$Premise, "Sprts","Sports")
df$Premise <- str_replace_all(df$Premise, "m,S","m or S")
df$Premise <- str_replace_all(df$Premise, "a,R","a or R")
df$Premise <- str_replace_all(df$Premise, "Auditor\\.","Auditoriums")
df$Premise <- str_replace_all(df$Premise, "ts Cra","ts & Cra")
df$Premise <- str_replace_all(df$Premise, "Pet$","Pet Stores")
df$Premise <- str_replace_all(df$Premise, "Out Build or Monument or UnderConst","Structure \\(Out Buildings,Monuments,Buildings Under Construction,Etc\\)")
df$Premise <- str_replace_all(df$Premise, "Apartment,Dorms","Apartment,Inn,Dorms,Boarding House")
df$Premise <- str_replace_all(df$Premise, "Occ Resd\\(House,Townhs,Dplex\\)","Occupancy Residence \\(Houses,Townhouses,Duplexes,Etc\\)")
df$Premise <- str_replace_all(df$Premise, "Fac \\(Barn,Garage,Warehouse\\)","Facility \\(Barns,Garages,Warehouses,Etc\\)")
df$Premise <- str_replace_all(df$Premise, "Amuse. Park,Bowl.","Amusement Park,Bowling")
df$Premise <- str_replace_all(df$Premise, "Daycare,Child","Daycare or Child")
df$Premise <- str_replace_all(df$Premise, "Factory,Manufacturing","Factory or Manufacturing")
df$Premise <- str_replace_all(df$Premise, "Nursery,Florist","Nursery or Florist")
df$Premise <- str_replace_all(df$Premise, "Physician's Office","Physician,Doctor,Dentist's Office")
df$Premise <- str_replace_all(df$Premise, " Of "," of ")
df$Premise <- str_replace_all(df$Premise, "Hotel,Motel,Etc","Hotel or Motel or Etc")

sort(unique(df$Premise))

ggplot(data=df) +
  geom_bar(aes(x=Premise)) +
  labs(title=paste("Incidents per premise, District",district)) +
  coord_flip()

reorder_size <- function(x) {
  factor(x, levels = names(sort(table(x))))
}
ggplot(df, aes(reorder_size(df$Premise))) + geom_bar() + coord_flip()

#   write out the cleaned premises so that a translation table may be created
#b <- sort(unique(df$Premise))
#write.table(b,file="~/Dropbox/CrimeStats/ptable.csv", row.names = FALSE, col.names = FALSE)
###########   editor magic happens
#   Read in translation table Premise to ShortPremise and add to df
ptab <- read_csv("~/mirrors/ajackson/crime/data/ptable.csv")
df <- left_join(df,ptab,by="Premise")
sort(table(df$ShortPremise),decreasing=TRUE)


```

```{r Check Block_Range}
#################################
# Block_Range
#################################
sort(unique(df$Block_Range))
df$Block_Range <- sub("^$","UNK", df$Block_Range)
```

```{r Check Type}
#################################
# Type
#################################

df$Type <- str_replace_all(df$Type," ","") 
df$Type <- str_replace_all(df$Type,"FWYSER","SER") 
```

```{r Check Street}
#################################
# Street
#################################
head(sort(unique(df$Street)),100)
#   copy Street to OldStreet to save it

##---new---##
df$OldStreet <- df$Street

##   test with df[grepl("TH\\s1$",df$Street),]

#####  Remove extra blanks, periods
# get rid of periods
df$Street <- str_replace_all(df$Street,"\\.","")
# get rid of doubled spaces, leading and trailing spaces
df$Street <- str_replace_all(df$Street,"\\s\\s"," ")
df$Street <- str_replace_all(df$Street,"^\\s+","")
df$Street <- str_replace_all(df$Street,"\\s+$","")
# get rid of apartment numbers and such
df$Street <- str_replace_all(df$Street," APT\\s*#*\\d*$","")
df$Street <- str_replace_all(df$Street," APT\\s*#*[A-Z]*$","")
df$Street <- str_replace_all(df$Street," APARTMENT\\s*#*[A-Z0-9]*$","")
df$Street <- str_replace_all(df$Street," SUITE\\s*#*[A-Z0-9]*$","")
df$Street <- str_replace_all(df$Street,"^#\\s?[A-Z]? ","")
df$Street <- str_replace_all(df$Street,"#\\s?[A-Z]?$","")
# clean up some one-offs
df$Street <- str_replace_all(df$Street," /STUDEWOOD ST$","")
df$Street <- str_replace(df$Street," STREET$"," ST")
df$Street <- str_replace(df$Street," STR$"," ST")
#   "7TH 1" to "7TH" and similar.
df$Street <- str_replace_all(df$Street,"TH\\s1$","TH")
#   "1" and "2" street becomes NA, since it makes no sense.
df$Street[grepl("^2$",df$Street)] <- NA
df$Street[grepl("^1$",df$Street)] <- NA
#   1-2 becomes 1/2
df$Street <- str_replace_all(df$Street,"1-2$","1/2")
#   If address is in Street field, extract it and create a block range from it
df$Street <- str_replace_all(df$Street,"-"," ")  # a little cleanup first
df$Street <- sub("^([0-9])+[A-Z]\\s","\\1 ", df$Street)  # a little cleanup first

mask <- grepl("^\\d{3,5}\\s",df$Street)
addrs <- str_extract(df$Street[mask],"^\\d{3,5}\\s")
addrs <- as.integer((as.integer(addrs)/100))*100
addrs <- paste(as.character(addrs), as.character(addrs+99),sep="-")
df$Block_Range[mask] <- addrs
df$Street <- str_replace_all(df$Street,"^\\d{3,5}\\s","")

#   add space between RD/TH/ST/ND and ST (2NDST -> 2ND ST)
df$Street <- sub("(\\d[RTSN][HSDT])ST","\\1 ST", df$Street)
#   get rid of stuff coming after "ST" - usually an apartment number
df$Street <- sub("(\\sST)\\s\\w+","\\1", df$Street)
df$Street <- sub("(\\sST)\\s\\w+","\\1", df$Street)
df$Street <- sub("(\\sST)/\\w+","\\1", df$Street)
df$Street <- sub("(\\sST)\\s[/# A-Z0-9]*","\\1", df$Street)
df$Street <- sub("(\\sST)E\\s[/# A-Z0-9]*","\\1", df$Street)
#   Similary for DRIVE, DR,   
df$Street <- sub("(\\sDRIVE)\\s\\w+","\\1", df$Street)
df$Street <- sub("(\\sDRIVE)\\s\\w+","\\1", df$Street)
df$Street <- sub("(\\sDR)\\s[/ A-Z0-9]*","\\1", df$Street)
df$Street <- sub("(\\sDR)\\s[/# A-Z0-9]*","\\1", df$Street)
df$Street <- str_replace(df$Street," DRIVE$"," DR")
#   And for RD
df$Street <- sub("(\\sRD)\\s[/ A-Z0-9]*","\\1", df$Street)
df$Street <- sub("(\\sRD)\\s[/# A-Z0-9]*","\\1", df$Street)
df$Street <- str_replace(df$Street," DRIVE$"," DR")
#   And for LANE and LN
df$Street <- sub("(\\sLANE)\\s[/ A-Z0-9]*","\\1", df$Street)
df$Street <- sub("(\\sLN)\\s[/ A-Z0-9]*","\\1", df$Street)
df$Street <- str_replace(df$Street," LANE$"," LN")
#   And for WAY
df$Street <- sub("(\\sWAY)\\s[/ A-Z0-9]*","\\1", df$Street)
#   And for BLVD
df$Street <- sub("(\\sBLVD)\\s[/ A-Z0-9]*","\\1", df$Street)
df$Street <- sub("(\\sBLVD)\\s*[/# A-Z0-9]*","\\1", df$Street)
#   And for CIRCLE
df$Street <- sub("(\\sCIRCLE)\\s[/ A-Z0-9]*","\\1", df$Street)
#   And for CT
df$Street <- sub("(\\sCT)\\s[/ A-Z0-9]*","\\1", df$Street)
#   And for PKWY
df$Street <- sub("(\\sPKWY)\\s[/ A-Z0-9]*","\\1", df$Street)
#   And for AVE
df$Street <- sub("(\\sAVE)\\s[/ A-Z0-9]*","\\1", df$Street)

#   Put ST/RD/DR/CT/BLVD/LN/AVE/CIRCLE/WAY into Type field and remove from Street field
mask <- grepl(" ST$| RD$| DR$| LN$| WAY$| BLVD$| CIRCLE$| CT$", df$Street)
masktype <- grepl("-", df$Type)
matched_values <- str_extract(df$Street[mask&masktype]," ST$| RD$| DR$| LN$| WAY$| BLVD$| CIRCLE$| CT$")
df$Type[mask&masktype] <- matched_values  #  put value into Type field
df$Street[mask&masktype] <- sub(" ST$| RD$| DR$| LN$| WAY$| BLVD$| CIRCLE$| CT$", "", df$Street[mask&masktype])  #  remove value from Street field
mask <- grepl(" ST$| RD$| DR$| LN$| WAY$| BLVD$| CIRCLE$| CT$| AVE$", df$Street)
matched_values <- str_extract(df$Street[mask]," ST$| RD$| DR$| LN$| WAY$| BLVD$| CIRCLE$| CT$| AVE$")
df$Type[mask] <- matched_values  #  put value into Type field
df$Street[mask] <- sub(" ST$| RD$| DR$| LN$| WAY$| BLVD$| CIRCLE$| CT$| AVE$", "", df$Street[mask])  #  remove value from Street field

####   Look for some more anomalies
# Remove digits at beginning of Street
df$Street <- str_replace(df$Street,"^[\\dO]*\\s","")
df$Street <- str_replace(df$Street,"^2ST$","2ND")
df$Street <- str_replace(df$Street,"^A EAST","EAST")
df$Street <- str_replace(df$Street,"^AVE ","AVENUE ")
df$Street <- str_replace(df$Street,"MEMORIAL DRPICNIC","MEMORIAL DR")
df$Street <- str_replace(df$Street,"AVENVUE OF OAKSST","AVENVUE OF OAKS")
df$Street <- str_replace(df$Street,"ALLEN PARKWAY AND WAUGH","WAUGH")
df$Street <- str_replace(df$Street,"A REBECCA","REBECCA")
df$Street <- str_replace(df$Street,"AVENUE C 12$","AVENUE C")
df$Street <- str_replace(df$Street,"^E 7 1$","E 7TH")
df$Street <- str_replace(df$Street,"^W 23$","W 23RD")
df$Street <- str_replace(df$Street,"^KOEHLER S 32$","KOEHLER")
#   remove more trailing numbers, but very carefully
maskdigits <- grepl("\\d$",df$Street)
maskhalf <- grepl("1/2$",df$Street)
maskHiway <- grepl("^IH |^FM |^TX |^I |HWY",df$Street)
df$Street[maskdigits&!maskhalf&!maskHiway] <- sub("\\s*\\d*$", "", df$Street[maskdigits&!maskhalf&!maskHiway])

df$Street <- str_replace(df$Street,"^B WEBER$","WEBER")
df$Street <- str_replace(df$Street,"^B KANSAS$","KANSAS")
df$Street <- str_replace(df$Street,"^C LAWRENCE$","LAWRENCE")
df$Street <- str_replace(df$Street,"^DARLINGST$","DARLING")
df$Street <- str_replace(df$Street,"^DURFORDST$","DURFORD")
df$Street <- str_replace(df$Street,"^DURHAM OBIB$","DURHAM")
df$Street <- str_replace(df$Street,"^MEMORIAL LOOP / ARNOT$","MEMORIAL LOOP")
df$Street <- str_replace(df$Street," \\*PARK$","")
df$Street <- str_replace(df$Street,"^ENTRANCE/W ","")
df$Street <- str_replace(df$Street,"TC JESTER","T C JESTER")
df$Street <- str_replace(df$Street,"FORESTER/USENER","FORESTER")
df$Street <- str_replace(df$Street,"HOGAN/N MAIN","HOGAN")
df$Street <- str_replace(df$Street,"HARDY/MCNEIL","MCNEIL")
df$Street <- str_replace(df$Street,"KATY FWY/TAYLOR","TAYLOR")
df$Street <- str_replace(df$Street,"LEE / TERRY","TERRY")
df$Street <- str_replace(df$Street,"2OTH","20TH")
df$Street <- str_replace(df$Street,"NMAIN","N MAIN")
df$Street <- str_replace(df$Street,"MCEWEN","MC EWEN")

#     Work on Direction indicators  and the Loop (N,S,E,W). LOOP wants spelled out
#     and allow for North Fwy, South Fwy, and East Fwy
df$Street <- str_replace(df$Street," LP "," LOOP ")
df$Street <- str_replace(df$Street," LP$"," LOOP")
maskloop <- grepl(" LOOP", df$Street)
maskfwy <- grepl("FWY", df$Type)
mask <- grepl(" FWY", df$Street)
maskfwy <- mask|maskfwy
mask <- grepl("^EAST ", df$Street)
df$Street[mask&!maskloop&!maskfwy] <- str_replace(df$Street[mask&!maskloop&!maskfwy], "^EAST ","E ")
mask <- grepl("^WEST ", df$Street)
df$Street[mask&!maskloop] <- str_replace(df$Street[mask&!maskloop], "^WEST ","W ")
mask <- grepl("^NORTH ", df$Street)
df$Street[mask&!maskloop&!maskfwy] <- str_replace(df$Street[mask&!maskloop&!maskfwy], "^NORTH ","N ")
mask <- grepl("^SOUTH ", df$Street)
df$Street[mask&!maskloop&!maskfwy] <- str_replace(df$Street[mask&!maskloop&!maskfwy], "^SOUTH ","S ")
#   Clean up freeways: "N LOOP FWY" is the canonical goal 
df$Street[maskloop] <- str_replace(df$Street[maskloop], "EAST$","E")
df$Street[maskloop] <- str_replace(df$Street[maskloop], "WEST$","W")
df$Street[maskloop] <- str_replace(df$Street[maskloop], "NORTH$","N")
df$Street[maskloop] <- str_replace(df$Street[maskloop], "SOUTH$","S")
#df$Street[maskloop] <- str_replace(df$Street[maskloop], "^E ","EAST ")
#df$Street[maskloop] <- str_replace(df$Street[maskloop], "^W ","WEST ")
#df$Street[maskloop] <- str_replace(df$Street[maskloop], "^N ","NORTH ")
#df$Street[maskloop] <- str_replace(df$Street[maskloop], "^S ","SOUTH ")

#   settle on Katy Fwy, Gulf Fwy, North, East, South FWY's, and LOOP instead of 610
df$Street <- str_replace(df$Street,"^I 45$","IH 45")
df$Street <- str_replace(df$Street,"^IH10","IH 10")
df$Street <- str_replace(df$Street,"FWY [IO]B","FWY") # remove InBound/OutBound flags
df$Street <- str_replace(df$Street," HOV","") # remove HOV flags
df$Street <- str_replace(df$Street,"IH 45 FWY","IH 45") # remove FWY
df$Street <- str_replace(df$Street,"IH 10 FWY","IH 10") # remove FWY
df$Street <- str_replace(df$Street,"(IH \\d+)\\s.*","\\1") # remove anything after number
df$Street <- str_replace(df$Street,"^\\w*\\s(IH \\d+)$","\\1") # remove anything before
###   for this district only does this work
df$Street <- str_replace(df$Street,"IH 10","KATY FWY") # Katy Fwy
df$Street <- str_replace(df$Street,"IH 45","NORTH FWY") # North Fwy
df$Street <- str_replace(df$Street,"IH 610","N LOOP FWY") # North Loop Fwy
df$Street <- str_replace(df$Street,"^LOOP$","N LOOP FWY") # North Loop Fwy
df$Street <- str_replace(df$Street,"^NORTH LOOP\\s\\w*$","N LOOP FWY") # North Loop Fwy
df$Street <- str_replace(df$Street,"^LOOP\\s\\w*$","N LOOP FWY") # North Loop Fwy
df$Street <- str_replace(df$Street,"^NLOOP\\s*\\w*$","N LOOP FWY") # North Loop Fwy
df$Street <- str_replace(df$Street,"^WLOOP\\s*\\w*$","W LOOP FWY") # West Loop Fwy
masksuffix <- grepl("N|S", df$Suffix)
maskloop <- grepl("NORTH LOOP", df$Street)
df$Street[maskloop&masksuffix] <- "WEST LOOP"
df$Street <- str_replace(df$Street,"^WEST LOOP\\s\\w*$","W LOOP FWY") # West Loop Fwy
df$Street <- str_replace(df$Street,"FREEWAY","FWY") 
df$Street <- str_replace(df$Street,"PKWY","PARKWAY") 
df$Street <- str_replace(df$Street,"PARKWAY\\s*[\\s\\w]*$","PARKWAY") # Get rid of suffixes
df$Street <- str_replace(df$Street,"FWY\\s*[\\s\\w]*$","FWY") # Get rid of suffixes
df$Street <- str_replace(df$Street,"^NORTHWEST$","NORTHWEST FWY") # 290
df$Street <- str_replace(df$Street,"^S US HWY 59$","SOUTHWEST FWY") # 59
df$Street <- str_replace(df$Street,"^HWY 249$","TX 249") # 249
df$Street <- str_replace(df$Street,"^TOMBALL$","TX 249") # 249

mask <- grepl("FWY",df$Type)
maskout <- grepl("FWY",df$Street)
df$Street[mask&!maskout] <- paste(df$Street[mask&!maskout],"FWY", sep=" ")
df$Street[grepl("^NA FWY$",df$Street)] <- NA
df$Street <- str_replace(df$Street,"^WEST LOOP FWY$","W LOOP FWY")

#############   done with freeways
df$Street <- str_replace(df$Street,"NPICNIC","N PICNIC") 
df$Street <- str_replace(df$Street,"PARK S","PARK SOUTH VIEW") 
df$Street <- str_replace(df$Street,"SHEPARD","N SHEPHERD") 
df$Street <- str_replace(df$Street,"SHEPHARD","N SHEPHERD") 
df$Street <- str_replace(df$Street,"VINCENTST","VINCENT") 
df$Street <- str_replace(df$Street,"YALEST","YALE") 
df$Street <- str_replace(df$Street,"REDANST","REDAN") 
df$Street <- str_replace(df$Street,"PARKVIEWST","PARKVIEW") 
df$Street <- str_replace(df$Street,"MOODYST","MOODY") 
df$Street <- str_replace(df$Street,"MAINST","MAIN") 
df$Street <- str_replace(df$Street,"LILLIANST","LILLIAN") 
df$Street <- str_replace(df$Street,"LACYST","LACY") 
df$Street <- str_replace(df$Street,"KEYST","KEY") 
df$Street <- str_replace(df$Street,"KANSASST","KANSAS") 
df$Street <- str_replace(df$Street,"JOHNSONST","JOHNSON") 
df$Street <- str_replace(df$Street,"GOSTICK","GOSTIC") 
df$Street <- str_replace(df$Street,"FUGATEST","FUGATE") 
df$Street <- str_replace(df$Street,"ENIDST","ENID") 
df$Street <- str_replace(df$Street,"ELMORAST","ELMORA") 
df$Street <- str_replace(df$Street,"CORTLANDTST","CORTLANDT") 
df$Street <- str_replace(df$Street,"CENTERST","CENTER") 
df$Street <- str_replace(df$Street,"CARLAST","CARLA") 
df$Street <- str_replace(df$Street,"AXILDAST","AXILDA") 
df$Street <- str_replace(df$Street,"ASBURYST","ASBURY") 
df$Street <- str_replace(df$Street,"ARMSTEADST","ARMSTEAD") 
df$Street <- str_replace(df$Street,"WALTONST","WALTON") 
df$Street <- str_replace(df$Street,"WAGNERST","WAGNER") 
df$Street <- str_replace(df$Street,"WATSONST","WATSON") 
df$Street <- str_replace(df$Street,"WALTWAY","WALT WAY") 
df$Street <- str_replace(df$Street,"WAVERLYST","WAVERLY") 
df$Street <- str_replace(df$Street,"WASHINGTO0N","WASHINGTON") 
df$Street <- str_replace(df$Street,"WCAVACADE","W CAVALCADE") 
df$Street <- str_replace(df$Street,"WICHMANN","WICHMAN") 
df$Street <- str_replace(df$Street,"WILLOWMOSS","WILLOW MOSS") 
df$Street <- str_replace(df$Street,"^W(\\d+)","W \\1") 

####################  temp
tail(head(sort(unique(df$Street)),600),100)



#   Kill off some that make no sense
df$Street[grepl("P\\s*O\\s*BOX\\s",df$Street)] <- NA
df$Street[grepl("^0 CHASE$",df$Street)] <- NA
df$Street[grepl("^1235$",df$Street)] <- NA
df$Street[grepl("^2A38E$",df$Street)] <- NA
df$Street[grepl("^1$",df$Street)] <- NA
df$Street[grepl("^32$",df$Street)] <- NA
df$Street[grepl("^31$",df$Street)] <- NA
df$Street[grepl("^61$",df$Street)] <- NA
df$Street[grepl("^A$",df$Street)] <- NA
df$Street[grepl("^AVENUE$",df$Street)] <- NA
df$Street[grepl("^AZALEA PARK$",df$Street)] <- NA
df$Street[grepl("^B$",df$Street)] <- NA
df$Street[grepl("^C$",df$Street)] <- NA
df$Street[grepl("^N$",df$Street)] <- NA
df$Street[grepl("^PARKWAY$",df$Street)] <- NA

########   Deal with Suffixes (N,S,E,W)
#mask <- grepl("N",df$Suffix)
#maskout <- grepl("KATY|FWY|LOOP|EAST|^N ", df$Street)
#df$Street[mask&!maskout] <- paste("N",df$Street[mask&!maskout],sep=" ")

#mask <- grepl("S",df$Suffix)
#maskout <- grepl("KATY|FWY|LOOP|EAST|^S ", df$Street)
#df$Street[mask&!maskout] <- paste("S",df$Street[mask&!maskout],sep=" ")

#mask <- grepl("E",df$Suffix)
#maskout <- grepl("KATY|FWY|LOOP|EAST|NORTH|^E ", df$Street)
#df$Street[mask&!maskout] <- paste("E",df$Street[mask&!maskout],sep=" ")
#df$Street[grepl("^E NA$",df$Street)] <- NA

#mask <- grepl("W",df$Suffix)
#maskout <- grepl("KATY|FWY|LOOP|EAST|NORTH|^W ", df$Street)
#df$Street[mask&!maskout] <- paste("W",df$Street[mask&!maskout],sep=" ")

```

```{r save the results}
#################################
# Save the results
#################################

saveRDS(df, file="~/Dropbox/CrimeStats/District2aReCleanData.rds")
```

