---
title: "Update Clean Data"
author: "Alan Jackson"
date: "January 13, 2019"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(stringr)

options(stringsAsFactors = FALSE)

Dictionary <- readRDS("~/Dropbox/CrimeStats/StreetDictionary.rds")

HoustonBoundary <- c(-95.789963, 29.518566, -95.005814, 30.117875)

knitr::opts_chunk$set(echo = TRUE)
```

## Update Clean Data

Take xxxxCleanData.rds files and add to them
  - OldAddress (Block + Suffix + Street + Type)
  - NewAddress (apply regex's to OldAddress to match census)
  - lat, long, MatchAddress
  - source (google, census, none)
  - status (good, out of area, gibberish, nonexistent, incomplete)
  - Block (census block)
  - Tract (census tract)

```{r define functions}

#     Create dictionary data frame of pattern/replacement
Makedict <- function(dictionary) {
  dict <- cbind.data.frame(split(dictionary, rep(1:2, times=length(dictionary)/2)), stringsAsFactors=F)
  names(dict) <- c("From", "To")
  return(dict)
}

#   test the searches first to see what they will find
testregex <- function(dframe, col, pat) { # input data frame and regex
  for(i in 1:length(pat[,1])) {
    print(paste("Pattern: ",pat[i,1]))
    hits <- unique(dframe[[col]][grepl(pat[i,1],dframe[[col]])])
    if (length(hits)>0){
      print(paste("   Result: ", hits))
    }
    else {
      print("No hits")
    }
  }
}

#   apply to input array
applyregex <- function(dframe, col, pat) {
  for(i in 1:length(pat[,1])) {
  dframe[[col]] <- str_replace_all(dframe[[col]],pat[i,1],pat[i,2])
  }
  return(dframe)
}

#   Following is sample of how to apply

#  dictionary <- c(
#                  " *P*O* BOX\\s\\d* *","",
#                  " *BOX\\s\\d* *","",
#                  "P *O BX",""
#  )
#  dict <- Makedict(dictionary)
#  #   test them first
#  testregex(df2, "Street", dict)
#  #   Apply
#  df2 <- applyregex(df2, "Street", dict)

```

##  Read in the files to be updated

```{r Read in data}


reclean <- c("District1aReCleanData.rds", 
             "District2aReCleanData.rds")
recleanpath <- "~/Dropbox/CrimeStats/"

dflist <- vector(mode = "list", length = 2)
for (i in 1:2) {
    dflist[[i]] <- readRDS(paste0(recleanpath, reclean[i]))
}

df <- dplyr::bind_rows(dflist)

  # first create addresses in df: 
  # Block_Range + Suffix + Street + Type + ", Houston, TX"

df$OldAddress <- paste(df$Block_Range, df$Suffix, df$Street, df$Type, ", Houston, TX")
df$OldAddress <- str_replace_all(df$OldAddress, "- ", "")
df$OldAddress <- str_replace_all(df$OldAddress, "  ", " ")

df$NewAddress <- paste(df$Block_Range, df$Suffix, df$Street, df$Type, ", Houston, TX")
df$NewAddress <- str_replace_all(df$NewAddress, "- ", "")
df$NewAddress <- str_replace_all(df$NewAddress, "  ", " ")

dict <- Makedict(Dictionary)
#   test them first
testregex(df, "NewAddress", dict)
#   Apply
df <- applyregex(df, "NewAddress", dict)
```

##  Set status where able

```{r set status preliminary}

#   If address contains an "UNK" then set status to "incomplete"

df <-  df %>% 
  mutate(status=if_else(grepl("^UNK ", NewAddress ), 
                "incomplete", 
                ""))

```



